desafioaeadw:
  target: dev
  outputs:
    dev:
      dataset: dbt_cintia
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/c/Users/carlo/Desktop/Cursos/cientistaDados_Lighthouse/Aulas_jornada_tecnica/Desafio_AE/desafioaeadw/desafioaeadw-2bd244b6dcbc.json
      location: US
      method: service-account
      priority: interactive
      project: desafioaeadw
      threads: 4
      type: bigquery